version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data.db"
