version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    networks:
      - symfony-network
    depends_on:
      - db
    entrypoint: [ "./wait-for-db.sh", "&&", "composer", "install", "--optimize-autoloader", "--no-dev", "&&", "apache2-foreground" ]


  db:
    image: postgres:16
    container_name: symfony_db
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: symfony_password
    ports:
      - "5432:5432"
    networks:
      - symfony-network
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  symfony-network:

volumes:
  db_data:
