version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"  # Change this to map localhost:8080 to Apache's port 80 inside the container
    networks:
      - symfony-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    ports:
      - "3306:3306"
    networks:
      - symfony-network
    volumes:
      - db_data:/var/lib/mysql

networks:
  symfony-network:

volumes:
  db_data:
