# name: Build and Deploy to DigitalOcean

# on:
#   push:
#     branches:
#       - main  # Deploys on push to the main branch

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Log in to GitHub Container Registry
#         run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

#       - name: Log in to DigitalOcean Container Registry
#         run: echo "${{ secrets.DO_API_TOKEN }}" | docker login registry.digitalocean.com -u ${{ secrets.DO_API_TOKEN }} --password-stdin

#       - name: Build Docker image
#         run: |
#           docker build -t ghcr.io/wkorol/symfony-app:latest .
#           docker tag ghcr.io/wkorol/symfony-app:latest registry.digitalocean.com/symfony-app/symfony-app:latest

#       # - name: Push to GitHub Container Registry
#       #   run: docker push ghcr.io/wkorol/symfony-app:latest

#       - name: Push to DigitalOcean Container Registry
#         run: docker push registry.digitalocean.com/symfony-app/symfony-app:latest

#       - name: Deploy to DigitalOcean App Platform
#         run: |
#           curl -X POST -H "Content-Type: application/json" \
#           -H "Authorization: Bearer ${{ secrets.DO_API_TOKEN }}" \
#           -d '{"spec": {"services": [{"name": "web", "image": {"registry_type": "DOCR", "registry": "registry.digitalocean.com", "repository": "symfony-app/symfony-app", "tag": "latest"}}]}}' \
#           https://api.digitalocean.com/v2/apps/${{ secrets.DO_APP_ID }}/deployments


#name: Build and Deploy to DigitalOcean
#
#on:
#  push:
#    branches:
#      - main  # Deploys on push to the main branch
#
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Log in to GitHub Container Registry
#        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
#
#      - name: Build Docker image
#        run: |
#          docker build -t ghcr.io/wkorol/symfony-app:latest .
#
#      - name: Push to GitHub Container Registry
#        run: docker push ghcr.io/wkorol/symfony-app:latest
#
#      - name: Trigger DigitalOcean App Redeployment
#        run: |
#          curl -X POST -H "Content-Type: application/json" \
#          -H "Authorization: Bearer ${{ secrets.DO_API_TOKEN }}" \
#          https://api.digitalocean.com/v2/apps/${{ secrets.DO_APP_ID }}/deployments

name: Build, Test, and Deploy Symfony App

on:
  push:
    branches:
      - main  # Trigger deploy on push to main branch

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: symfony
          POSTGRES_USER: symfony_user
          POSTGRES_PASSWORD: symfony_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U symfony_user" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    env:
      DATABASE_URL: "postgresql://symfony_user:symfony_password@localhost:5432/symfony"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: |
          docker build --target deps -t symfony-app-deps .

      - name: Log in to GitHub Container Registry
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
        run: echo "${GHCR_PAT}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/wkorol/symfony-app:latest .

      - name: Push to GitHub Container Registry
        run: docker push ghcr.io/wkorol/symfony-app:latest

      - name: Deploy to DigitalOcean
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
          DO_APP_ID: ${{ secrets.DO_APP_ID }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${DO_API_TOKEN}" \
          https://api.digitalocean.com/v2/apps/${DO_APP_ID}/deployments

